import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('../../..', import.meta.url)));
const tokens = JSON.parse(await readFile(resolve(root, 'packages/design_tokens/tokens.json'), 'utf8'));
const check = process.argv.includes('--check');
const outputs = new Map();
const kebab = (value) => value
  .replace(/^chart(\d)$/, 'chart-$1')
  .replace(/^rail(\d)/, 'rail-$1')
  .replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
const cssVars = (colors) => Object.entries(colors).map(([name, value]) => `  --${kebab(name)}: ${value};`).join('\n');
const sharedCss = `  --radius: ${tokens.radius.cssRoot};\n  --panel-alpha: ${tokens.surface.panelAlpha};`;
const cssTokens = `  --text-2xs: ${tokens.typography.sizesPx['2xs']}px;\n  --text-2xs--line-height: ${tokens.typography.bodyLineHeight};\n${Object.entries(tokens.typography.sizesPx).map(([name, value]) => `  --text-${name}: ${value}px;`).join('\n')}\n${tokens.spacing.allowed.map((value, index) => `  --ds-space-${index}: ${value}px;`).join('\n')}\n  --state-success: var(--success);\n  --state-info: var(--info);\n  --state-warning: var(--amber);\n  --state-destructive: var(--destructive);\n  --state-neutral: var(--muted);`;

outputs.set(resolve(root, 'packages/design_tokens/react/tokens.css'),
  `/* Generated by packages/design_tokens/tool/generate.mjs. Do not edit. */\n:root,\n.light {\n${cssVars(tokens.colors.light)}\n${sharedCss}\n${cssTokens}\n}\n\n.dark {\n${cssVars(tokens.colors.dark)}\n}\n`);
outputs.set(resolve(root, 'packages/design_tokens/react/tokens.ts'),
  `/* Generated by packages/design_tokens/tool/generate.mjs. Do not edit. */\nexport const designTokens = ${JSON.stringify({ version: tokens.version, source: tokens.source, ruleIds: tokens.ruleIds, colors: tokens.colors, typography: tokens.typography, spacing: tokens.spacing, states: tokens.states, radius: tokens.radius, surface: tokens.surface }, null, 2)} as const;\n`);

const dartHex = (value) => {
  if (value.startsWith('#')) return `0xFF${value.slice(1)}`;
  const match = value.match(/^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$/);
  if (!match) throw new Error(`Unsupported color token: ${value}`);
  const [, red, green, blue, alpha] = match;
  const channel = (part) => Number(part).toString(16).padStart(2, '0');
  return `0x${channel(Math.round(Number(alpha) * 255))}${channel(red)}${channel(green)}${channel(blue)}`;
};
const dartColors = (mode, colors) => Object.entries(colors)
  .map(([name, value]) => `  static const ${mode}${name[0].toUpperCase()}${name.slice(1)} = Color(${dartHex(value)});`)
  .join('\n');
const spacingSteps = [0, 0.5, 1, 1.5, 2, 2.5, 3, 4, 6, 8, 12];
const dartSpacing = spacingSteps.map((step, index) => `  static const space${String(step).replace('.', '_')} = ${tokens.spacing.allowed[index]}.0;`).join('\n');
const dart = `// Generated by packages/design_tokens/tool/generate.mjs. Do not edit.\nimport 'package:flutter/material.dart';\n\nabstract final class ConstructionTokens {\n  static const version = ${tokens.version};\n\n${dartColors('light', tokens.colors.light)}\n\n${dartColors('dark', tokens.colors.dark)}\n\n${dartSpacing}\n  static const fontFamilySans = '${tokens.typography.fontFamily.sans.flutter}';\n  static const fontFamilyMono = '${tokens.typography.fontFamily.mono.flutter}';\n  static const fontFamilyRail = '${tokens.typography.fontFamily.rail.flutter}';\n  static const fontSize2xs = ${tokens.typography.sizesPx['2xs']}.0;\n  static const fontSizeXs = ${tokens.typography.sizesPx.xs}.0;\n  static const fontSizeSm = ${tokens.typography.sizesPx.sm}.0;\n  static const fontSizeBase = ${tokens.typography.sizesPx.base}.0;\n  static const fontSizeLg = ${tokens.typography.sizesPx.lg}.0;\n  static const fontSizeXl = ${tokens.typography.sizesPx.xl}.0;\n  static const fontSize2xl = ${tokens.typography.sizesPx['2xl']}.0;\n  static const interactiveMinimumPx = ${tokens.typography.interactiveMinimumPx}.0;\n  static const inputMinimumPx = ${tokens.typography.inputMinimumPx}.0;\n  static const bodyLineHeight = ${tokens.platformSpecific['typography.body.lineHeight'].flutter};\n  static const controlRadius = ${tokens.radius.controlPx}.0;\n  static const cardRadius = ${tokens.radius.cardPx}.0;\n}\n`;
outputs.set(resolve(root, 'packages/construction_ui/lib/src/generated_tokens.dart'), dart);

let stale = false;
for (const [path, content] of outputs) {
  if (check) {
    let existing;
    try { existing = await readFile(path, 'utf8'); } catch { existing = null; }
    if (existing !== content) { console.error(`Stale generated token artifact: ${path}`); stale = true; }
  } else {
    await writeFile(path, content);
    console.log(`Wrote ${path.slice(root.length + 1)}`);
  }
}
if (stale) process.exitCode = 1;
